name: Gradle CI

on:
  
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
    - master
    paths:
    - "VariantCaller/**"

jobs:
  build:
    
    name: Building and testing
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Grant execute permission for gradlew
      working-directory: ./VariantCaller
      run: chmod +x ./gradlew
    
    - name: Build and test project
      working-directory: ./VariantCaller
      run: ./gradlew build

    - name: Run Integration test
      working-directory: ./VariantCaller
      run: ./gradlew integrationTest
